### PR TITLE
l18n_ja.ts: update

### PR DESCRIPTION
**Pull request by LionNatsu**
Relevant: #28

### CODE REVIEW

**Comment by LionNatsu** [comment]
CC: @KireinaHoro 
Emm.. how do you think?

**Comment by Harry-Chen** [comment]
Please pull the latest commit from upstream and I'll merge that.
Now the file should be renamed to 'ja_JP.ts'

**Comment by KireinaHoro** [comment]
@LionNatsu
Well, actually I'm not quite clear when to use a verb and when to use a noun. What are the differences?

**Comment by LionNatsu** [comment]
@KireinaHoro In short, when they are placed in a menu, *verbs with suffix する* should be used in noun form (without that suffix). Because of they should be very concise in such context.

**Comment by KireinaHoro** [comment]
@LionNatsu I see. Thanks!

**Pull request merged**
